### PR TITLE
Bring the front-end pages from the other repo

### PR DESCRIPTION
**Pull request by ardeshirj**
For ticket #12

### CODE REVIEW

**Comment by lewisric** [comment]
Looks solid to me

**Comment by lewisric** [comment]
@beazley2 @sector46 @CATcommander 

Quick review please so we can get this merged

**Comment by beazley2** [comment]
Looks fine to me. Just to be clear, not worried about full connection yet right? Home page doesn't access database.

**Comment by lewisric** [comment]
That is correct that is not part of this story, and it will be an integration later

**Pull request merged**
